name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag jhonesto:igpt
    
    - name: Push to dockerhub registry
      run: |
        echo "${{ secrets.DOCKERHUB }}" | docker login -u jhonesto --password-stdin
        docker push jhonesto/igpt:latest
